### ISSUE TITLE
missing softlinks for libraries

### ISSUE THREAD

**Issue by LightningLars** [OpenFOAM/OpenFOAM-3.0.x#1]
Hello,
cant compile OF3.0.x, there are a lot of links for header files missing in src/OpenFOAM/lnInclude.

Greets,
Ferdi

**Comment by OpenFOAM** [comment]
Dear Ferdi,

> cant compile OF3.0.x, there are a lot of links for header files missing in src/
> OpenFOAM/lnInclude.

The lnInclude directories are built automatically by wmake.  If for some reason
they are incomplete then something in there creation failed, maybe due to errors
in your filing system.  Simply clear them out with wcleanLnIncludeAll and
recompile.

-- 
Best regards,

Henry

Henry G. Weller
The OpenFOAM Foundation

Email: h.weller@openfoam.org
URL: http://www.openfoam.org

**Comment by LightningLars** [comment]
Thanks Henry,
didnt know that. First time i had this Issue; on different platforms so i thought there is sth. wrong.

Thank you very much!
